name: Build with Alire
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: alire-project/setup-alire@v4
        with:
          version: nightly
          toolchain: gnat_arm_elf gprbuild
      - run:
          cd test;
          alr build --validation;
